# Backbone for the open Phyloplate tree. Ages in Ma, with the source for each node.
STR21 = "Strassert et al. 2021 Nat Commun 12:1879 (MCMCTree AC, Amorphea root, uniform calibrations; mean posterior)"
IRI17 = "Irisarri et al. 2017 Nat Ecol Evol 1:1370 (genome-averaged timetree of jawed vertebrates)"
YANG16 = "Yang et al. 2016 Sci Rep 6:21361 (florideophyte red algae timetree)"
APPROX = "APPROXIMATE, not yet cited; replace"
WOLFE19 = "Wolfe et al. 2019 Proc R Soc B 286:20190079, PhyloBayes UGAM chronogram;"
# Subtrees (S) keep their own internal ages and hang from the enclosing node at their crown age.
# Rule: a source's crown wins over a backbone node for the same split; backbone ages apply only above it.
# Nodes with no source or species under them persist as placeholders so curation.PLACEMENTS_OPEN can anchor families to them.
OPEN = "/home/claude/open/"
import csv as _csv

SB18_SYN = {"Achnatherum hymenoides": "Eriocoma hymenoides", "Amomum tsao-ko": "Lanxangia tsaoko",
            "Chaenomeles sinensis": "Pseudocydonia sinensis", "Erythranthe guttata": "Mimulus guttatus",
            "Cheilocostus speciosus": "Hellenia speciosa"}
RAB18_SYN = {"Liza haematocheila": "Planiliza haematocheila", "Chelon haematocheilus": "Planiliza haematocheila",
             "Sciaena gilberti": "Cilus gilberti", "Channa obscura": "Parachanna obscura"}
UPH19_SYN = {"Bubalus arnee": "Bubalus bubalis", "Tragelaphus oryx": "Taurotragus oryx", "Equus africanus": "Equus asinus",
             "Macropus rufus": "Osphranter rufus", "Macropus rufogriseus": "Notamacropus rufogriseus"}
VAR19_SYN = {"Polyporus squamosus": "Cerioporus squamosus"}
for _r in _csv.DictReader(open(OPEN + "Species_name_match.csv", encoding="utf-8"), delimiter="\t"):
    _a, _f = _r["Alignment_names"].replace("_", " "), _r["Species_names_final"].replace("_", " ")
    if _a != _f: VAR19_SYN.setdefault(_a, _f)
JETZ12_SYN = {"Puffinus griseus": "Ardenna grisea", "Puffinus tenuirostris": "Ardenna tenuirostris",
              "Larus ridibundus": "Chroicocephalus ridibundus", "Anas penelope": "Mareca penelope",
              "Anas strepera": "Mareca strepera", "Anas clypeata": "Spatula clypeata", "Tetrao tetrix": "Lyrurus tetrix",
              "Bonasa bonasia": "Tetrastes bonasia", "Francolinus capensis": "Pternistis capensis",
              "Collocalia fuciphaga": "Aerodramus fuciphagus"}

TREE = N("Eukaryotes", 2132, STR21,
  N("Amorphea", 1938, STR21,
    N("Opisthokonta", 1359, STR21,
      N("Fungi", 806, STR21,
        N("Mucoromycota + Dikarya", 700, APPROX + " (Mucoromycota stem; fungal timetree 2025 gives 701-1114 for the LCA)",
          N("Dikarya", 646, STR21,
            N("Ascomycota", 493, STR21,
              N("Saccharomycotina + Pezizomycotina", 450, APPROX,
                N("Saccharomycotina", 350, APPROX),
                N("Pezizomycotina", 400, APPROX,
                  N("Pezizales", 300, APPROX + " (literature 248-441)"),
                  N("Leotiomyceta", 320, APPROX,
                    N("Eurotiomycetes", 150, APPROX),
                    N("Sordariomycetes", 250, APPROX,
                      N("Hypocreales", 150, APPROX),
                    ),
                  ),
                ),
              ),
            ),
            N("Basidiomycota", 452, STR21,
              S(OPEN + "varga2019.tree", "Varga et al. 2019 Nat Ecol Evol 3:668, FastDate chronogram 216 (5,284 Agaricomycotina)", VAR19_SYN),
            ),
          ),
        ),
      ),
      N("Animals", 688, STR21,
        N("Cnidaria + Bilateria", 651, STR21,
          N("Cnidaria", 620, APPROX + " (Anthozoa vs Medusozoa; Park et al. 2012 give 741, above the STR21 stem)"),
          N("Bilateria", 616, STR21,
            N("Protostomes", 592, STR21,
              N("Ecdysozoa", 585, APPROX,
                N("Arthropoda", 555, APPROX + " (cf. Lozano-Fernandez et al. 2016)",
                  N("Chelicerata", 480, APPROX,
                    N("Arachnida", 450, APPROX),
                  ),
                  N("Mandibulata", 545, APPROX,
                    N("Pancrustacea", 520, APPROX + " (cf. Misof et al. 2014)",
                      N("Multicrustacea", 510, APPROX,
                        N("Cirripedia", 300, APPROX),
                        N("Malacostraca", 490, APPROX + " (Wolfe et al. 2019 stomatopod/decapod split 466-480)",
                          N("Eumalacostraca", 480, APPROX,
                           N("Eucarida", 470, APPROX,
                            N("Decapoda", 465, WOLFE19 + " 465 (CIR 455)",
                              N("Dendrobranchiata", 349, WOLFE19 + " 349 (CIR 361)"),
                              N("Pleocyemata", 461, WOLFE19 + " 461 (CIR 454)",
                                N("Caridea", 415, WOLFE19 + " 415 (CIR 432)"),
                                N("Reptantia", 402, WOLFE19 + " 402 (CIR 393)",
                                  N("Achelata", 250, WOLFE19 + " 250 (CIR 254)",
                                    N("Palinuridae", 110, WOLFE19 + " Panulirus vs Palinurus 110 (CIR 167)"),
                                  ),
                                  N("Astacidea", 223, WOLFE19 + " 223 (CIR 322; models disagree)",
                                    N("Crayfish (Astacoidea + Parastacoidea)", 149, WOLFE19 + " Procambarus vs Cherax 149 (CIR 241)"),
                                  ),
                                  N("Meiura", 322, WOLFE19 + " 322 (CIR 329)",
                                    N("Anomura", 197, WOLFE19 + " 197 (CIR 206)"),
                                    N("Brachyura", 183, WOLFE19 + " 183 (CIR 162)",
                                      N("Eubrachyura", 102, WOLFE19 + " 102 (CIR 118)"),
                                    ),
                                  ),
                                ),
                              ),
                            ),
                          ),
                        ),
                      ),
                      ),
                      N("Hexapoda", 480, APPROX + " (cf. Misof et al. 2014)",
                        N("Insecta", 440, APPROX,
                          N("Neoptera", 380, APPROX,
                            N("Polyneoptera", 350, APPROX,
                              N("Orthoptera", 300, APPROX),
                            ),
                            N("Eumetabola", 370, APPROX,
                              N("Hemiptera", 300, APPROX,
                                N("Heteroptera", 250, APPROX),
                              ),
                              N("Holometabola", 345, APPROX + " (cf. Misof et al. 2014)",
                                N("Hymenoptera", 280, APPROX + " (cf. Peters et al. 2017)",
                                  N("Aculeata", 200, APPROX,
                                    N("Apoidea + Formicoidea", 180, APPROX),
                                  ),
                                ),
                                N("Aparaglossata", 330, APPROX,
                                  N("Coleoptera", 300, APPROX),
                                  N("Panorpida", 300, APPROX,
                                    N("Diptera", 240, APPROX),
                                    N("Lepidoptera", 250, APPROX + " (cf. Kawahara et al. 2019)",
                                      N("Obtectomera", 150, APPROX,
                                        N("Bombycoidea", 90, APPROX),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ),
                          ),
                        ),
                      ),
                    ),
                  ),
                ),
              ),
              N("Lophotrochozoa", 564, STR21,
                N("Annelida", 520, APPROX),
                N("Mollusca", 534, STR21,
                  N("Conchifera", 520, APPROX,
                    N("Bivalvia", 480, APPROX,
                      N("Pteriomorphia", 450, APPROX),
                      N("Heterodonta", 400, APPROX,
                        N("Imparidentia", 300, APPROX),
                      ),
                    ),
                    N("Gastropoda", 450, APPROX,
                      N("Orthogastropoda", 420, APPROX,
                        N("Vetigastropoda", 350, APPROX),
                        N("Apogastropoda", 400, APPROX,
                          N("Caenogastropoda", 300, APPROX,
                            N("Neogastropoda", 150, APPROX),
                          ),
                          N("Heterobranchia", 300, APPROX,
                            N("Stylommatophora", 150, APPROX),
                          ),
                        ),
                      ),
                    ),
                    N("Coleoidea", 260, APPROX + " (cf. Tanner et al. 2017)",
                      N("Octopoda", 150, APPROX),
                      N("Decapodiformes", 180, APPROX),
                    ),
                  ),
                ),
              ),
            ),
            N("Deuterostomes", 599, STR21,
              N("Echinodermata", 500, APPROX,
                N("Echinozoa", 450, APPROX,
                  N("Echinoidea", 250, APPROX),
                  N("Holothuroidea", 250, APPROX),
                ),
              ),
              N("Chordates", 560, STR21,
                N("Olfactores", 545, APPROX,
                  N("Tunicata", 300, APPROX),
                  N("Vertebrates", 535, APPROX + " (cyclostome/gnathostome split)",
                    N("Cyclostomata", 480, APPROX),
                    N("Jawed vertebrates", 458, IRI17,
                      S(OPEN + "sharks_vertlife.nwk", "Stein et al. 2018 Nat Ecol Evol 2:288, VertLife shark tree subset (Chond_10Cal), tree 1 of 100", {"Raja binoculata": "Beringraja binoculata", "Himantura gerrardi": "Maculabatis gerrardi"}),
                      N("Bony vertebrates", 449, IRI17,
                        S(OPEN + "actinopt_12k_treePL_tre", "Rabosky et al. 2018 Nature 559:392, Fish Tree of Life actinopt_12k_treePL", RAB18_SYN),
                        N("Lobe-finned fishes + tetrapods", 412, IRI17,
                          T("Protopterus annectens"),
                          N("Tetrapods", 350, IRI17 + " (early Carboniferous; mean approx.)",
                            S(OPEN + "amphibians_vertlife.nwk", "Jetz & Pyron 2018 Nat Ecol Evol 2:850, VertLife amphibian tree subset, tree 1 of 100", {}),
                            N("Amniotes", 325, STR21,
                              S(OPEN + "mamphy_mcc.nwk", "Upham et al. 2019 PLoS Biol 17:e3000494, MamPhy completed 5,911sp NDexp MCC", UPH19_SYN),
                              N("Sauropsids", 280, APPROX + " (lepidosaur/archosaur split)",
                                S(OPEN + "squamates_vertlife.nwk", "Tonini et al. 2016 Biol Conserv 204:23, VertLife squamate tree subset, tree 1 of 100", {}),
                                N("Archosaurs + turtles", 260, APPROX,
                                  N("Testudines", 200, APPROX),
                                  N("Archosaurs", 250, APPROX + " (crocodilians vs birds)",
                                    N("Crocodylia", 90, APPROX),
                                    S(OPEN + "birds_jetz_tree1.nwk", "Jetz et al. 2012 Nature 491:444, birdtree.org Ericson Stage 2 subset, tree 1 of 100", JETZ12_SYN),
                                  ),
                                ),
                              ),
                            ),
                          ),
                        ),
                      ),
                    ),
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    ),
  ),
  N("Diaphoretickes + Discoba", 2114, STR21,
    N("Discoba", 1674, STR21, T("Euglena gracilis")),
    N("Diaphoretickes", 2028, STR21,
      N("SAR", 1741, STR21,
        N("Stramenopiles", 1044, STR21,
          N("Phaeophyceae", 190, APPROX + " (cf. Silberfeld et al. 2010, 155-200)",
            N("Ectocarpales + BACR", 150, APPROX,
              N("BACR", 100, APPROX,
                N("Laminariales", 30, APPROX),
                N("Fucales", 60, APPROX),
              ),
            ),
          ),
        ),
      ),
      N("Archaeplastida", 1925, STR21,
        N("Rhodophyta", 1614, STR21,
          N("Bangiophyceae + Florideophyceae", 1415, STR21,
            N("Bangiales", 100, APPROX),
            N("Florideophyceae", 943, YANG16,
              N("Nemaliophycidae", 500, APPROX + " (subclass split 661 in " + YANG16 + ")"),
              N("Ahnfeltiophycidae + Rhodymeniophycidae", 508, YANG16,
                N("Rhodymeniophycidae", 450, APPROX,
                  N("Ceramiales", 335, YANG16),
                  N("Gigartinales + Gracilariales + Halymeniales", 400, APPROX,
                    N("Gigartinales", 250, APPROX),
                  ),
                ),
              ),
            ),
          ),
        ),
        N("Viridiplantae", 1112, STR21,
          N("Chlorophyta", 972, STR21,
            N("Core Chlorophyta (UTC)", 600, STR21 + " (node 206, Coccomyxa vs Volvox = 583; rounded)",
              N("Ulvophyceae", 450, APPROX,
                N("Ulvales", 150, APPROX),
                N("Bryopsidales", 200, APPROX),
              ),
              N("Trebouxiophyceae", 400, APPROX),
              N("Chlorophyceae", 400, APPROX),
            ),
          ),
          N("Streptophyta", 790, STR21,
            N("Land plants", 534, STR21,
              N("Euphyllophytes", 480, STR21 + " (474; raised to 480 to sit above FTOL's fern crown of 475)",
                S(OPEN + "ftol_dated.nwk", "Nitta et al. 2022 Front Plant Sci, FTOL ML dated tree (ftolr)", {}, groups=["Ferns"]),
                S(OPEN + "v0.1/ALLMB.tre", "Smith & Brown 2018 Am J Bot 105:302, ALLMB (seed plants, Magallon backbone)", SB18_SYN),
              ),
            ),
          ),
        ),
      ),
    ),
  ),
)
