# Backbone for the open Phyloplate tree. Ages in Ma, with the source for each node.
STR21 = "Strassert et al. 2021 Nat Commun 12:1879 (MCMCTree AC, Amorphea root, uniform calibrations; mean posterior)"
IRI17 = "Irisarri et al. 2017 Nat Ecol Evol 1:1370 (genome-averaged timetree of jawed vertebrates)"
YANG16 = "Yang et al. 2016 Sci Rep 6:21361 (florideophyte red algae timetree)"
APPROX = "APPROXIMATE, not yet cited; replace"
MISOF14 = "Misof et al. 2014 Science 346:763 (1KITE insect timetree);"
PETERS17 = "Peters et al. 2017 Curr Biol 27:1013 (Hymenoptera timetree);"
KAWA19 = "Kawahara et al. 2019 PNAS 116:22657 (Lepidoptera timetree);"
CHOI24 = "Choi et al. 2024 Curr Biol 34:740 (plastome brown algal timetree, uncorrelated clock, 8 fossil calibrations; Table 3);"
SHEN20 = "Shen et al. 2020 Sci Adv 6:eabd0079 (1,107-genome Ascomycota timetree, RelTime, six calibrations);"
TT5 = "TimeTree 5 (Kumar et al. 2022 Mol Biol Evol 39:msac174), median of published estimates; used by permission of the TimeTree team, 2026-09-21;"
TANNER17 = "Tanner et al. 2017 Proc R Soc B 284:20162818 (180-gene cephalopod timetree, CIR clock, 12 calibrations; Suppl. Table 2 and Fig. S4);"
ZHANG22 = "Frontiers Ecol Evol 2022, 10.3389/fevo.2022.973485 (mitogenomic gastropod timetree, ML dating);"
LI25 = "Li et al. 2025 Syst Biol 74:16 (UCE bivalve timetree, MCMCTree, 18 calibrations from Crouch et al. 2021);"
WOLFE19 = "Wolfe et al. 2019 Proc R Soc B 286:20190079, PhyloBayes UGAM chronogram;"
# Subtrees (S) keep their own internal ages and hang from the enclosing node at their crown age.
# Rule: a source's crown wins over a backbone node for the same split; backbone ages apply only above it.
# Nodes with no source or species under them persist as placeholders so curation.PLACEMENTS_OPEN can anchor families to them.
OPEN = "/home/claude/open/"
import csv as _csv

SB18_SYN = {"Achnatherum hymenoides": "Eriocoma hymenoides", "Amomum tsao-ko": "Lanxangia tsaoko",
            "Chaenomeles sinensis": "Pseudocydonia sinensis", "Erythranthe guttata": "Mimulus guttatus",
            "Cheilocostus speciosus": "Hellenia speciosa"}
RAB18_SYN = {"Liza haematocheila": "Planiliza haematocheila", "Chelon haematocheilus": "Planiliza haematocheila",
             "Sciaena gilberti": "Cilus gilberti", "Channa obscura": "Parachanna obscura"}
UPH19_SYN = {"Bubalus arnee": "Bubalus bubalis", "Tragelaphus oryx": "Taurotragus oryx", "Equus africanus": "Equus asinus",
             "Macropus rufus": "Osphranter rufus", "Macropus rufogriseus": "Notamacropus rufogriseus"}
VAR19_SYN = {"Polyporus squamosus": "Cerioporus squamosus"}
for _r in _csv.DictReader(open(OPEN + "Species_name_match.csv", encoding="utf-8"), delimiter="\t"):
    _a, _f = _r["Alignment_names"].replace("_", " "), _r["Species_names_final"].replace("_", " ")
    if _a != _f: VAR19_SYN.setdefault(_a, _f)
JETZ12_SYN = {"Puffinus griseus": "Ardenna grisea", "Puffinus tenuirostris": "Ardenna tenuirostris",
              "Larus ridibundus": "Chroicocephalus ridibundus", "Anas penelope": "Mareca penelope",
              "Anas strepera": "Mareca strepera", "Anas clypeata": "Spatula clypeata", "Tetrao tetrix": "Lyrurus tetrix",
              "Bonasa bonasia": "Tetrastes bonasia", "Francolinus capensis": "Pternistis capensis",
              "Collocalia fuciphaga": "Aerodramus fuciphagus"}

TREE = N("Eukaryotes", 2132, STR21,
  N("Amorphea", 1938, STR21,
    N("Opisthokonta", 1359, STR21,
      N("Fungi", 806, STR21,
        N("Mucoromycota + Dikarya", 700, APPROX + " (Mucoromycota stem; fungal timetree 2025 gives 701-1114 for the LCA)",
          N("Dikarya", 646, STR21,
            S(OPEN + "shen2020_asco.nwk", "Shen et al. 2020 Sci Adv 6:eabd0079, 1,107-genome Ascomycota timetree (RelTime, 815 genes; exact times)", {"Galactomyces candidus": "Geotrichum candidum"}, groups=["Fungi"]),
            N("Basidiomycota", 452, STR21,
              S(OPEN + "varga2019.tree", "Varga et al. 2019 Nat Ecol Evol 3:668, FastDate chronogram 216 (5,284 Agaricomycotina)", VAR19_SYN),
            ),
          ),
        ),
      ),
      N("Animals", 688, STR21,
        N("Cnidaria + Bilateria", 651, STR21,
          N("Cnidaria", 620, APPROX + " (Anthozoa vs Medusozoa; Park et al. 2012 give 741, above the STR21 stem)"),
          N("Bilateria", 616, STR21,
            N("Protostomes", 592, STR21,
              N("Ecdysozoa", 585, APPROX,
                N("Arthropoda", 555, APPROX + " (cf. Lozano-Fernandez et al. 2016)",
                  N("Chelicerata", 480, APPROX,
                    N("Arachnida", 450, APPROX),
                  ),
                  N("Mandibulata", 545, APPROX,
                    N("Pancrustacea", 520, APPROX + " (cf. Misof et al. 2014)",
                      N("Multicrustacea", 510, APPROX,
                        N("Cirripedia", 193, TT5 + " barnacle crown 193; my prior guess 300"),
                        N("Malacostraca", 490, APPROX + " (Wolfe et al. 2019 stomatopod/decapod split 466-480)",
                          N("Eumalacostraca", 480, APPROX,
                           N("Eucarida", 470, APPROX,
                            N("Decapoda", 465, WOLFE19 + " 465 (CIR 455)",
                              N("Dendrobranchiata", 349, WOLFE19 + " 349 (CIR 361)"),
                              N("Pleocyemata", 461, WOLFE19 + " 461 (CIR 454)",
                                N("Caridea", 415, WOLFE19 + " 415 (CIR 432)"),
                                N("Reptantia", 402, WOLFE19 + " 402 (CIR 393)",
                                  N("Achelata", 250, WOLFE19 + " 250 (CIR 254)",
                                    N("Palinuridae", 110, WOLFE19 + " Panulirus vs Palinurus 110 (CIR 167)"),
                                  ),
                                  N("Astacidea", 223, WOLFE19 + " 223 (CIR 322; models disagree)",
                                    N("Crayfish (Astacoidea + Parastacoidea)", 149, WOLFE19 + " Procambarus vs Cherax 149 (CIR 241)"),
                                  ),
                                  N("Meiura", 322, WOLFE19 + " 322 (CIR 329)",
                                    N("Anomura", 197, WOLFE19 + " 197 (CIR 206)"),
                                    N("Brachyura", 183, WOLFE19 + " 183 (CIR 162)",
                                      N("Eubrachyura", 102, WOLFE19 + " 102 (CIR 118)"),
                                    ),
                                  ),
                                ),
                              ),
                            ),
                          ),
                        ),
                      ),
                      ),
                      N("Hexapoda", 479, MISOF14 + " origin of insects ~479 (Early Ordovician)",
                        N("Insecta", 440, APPROX + " (Archaeognatha split; Misof et al. 2014 give ~441)",
                         N("Pterygota", 406, MISOF14 + " insect flight ~406 (Early Devonian)",
                          N("Neoptera", 373, APPROX + " (cf. Misof et al. 2014)",
                            N("Polyneoptera", 350, APPROX,
                              N("Orthoptera", 300, APPROX),
                            ),
                            N("Eumetabola", 370, APPROX,
                              N("Hemiptera", 300, APPROX,
                                N("Heteroptera", 250, APPROX),
                              ),
                              N("Holometabola", 345, MISOF14 + " major extant lineages ~345 (Mississippian)",
                                N("Hymenoptera", 281, PETERS17 + " crown Hymenoptera ~281",
                                  N("Aculeata", 200, APPROX,
                                    N("Apoidea + Formicoidea", 180, APPROX),
                                  ),
                                ),
                                N("Aparaglossata", 338, APPROX + " (must sit below Holometabola 345)",
                                  N("Coleoptera", 300, APPROX),
                                  N("Panorpida", 320, APPROX + " (Diptera vs Lepidoptera; must sit above Lepidoptera crown 300)",
                                    N("Diptera", 240, APPROX),
                                    N("Lepidoptera", 300, KAWA19 + " crown Lepidoptera ~300 (Late Carboniferous)",
                                      N("Ditrysia", 210, APPROX,
                                        N("Obtectomera", 150, APPROX,
                                          N("Bombycoidea", 90, APPROX),
                                        ),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ),
                          ),
                         ),
                        ),
                      ),
                    ),
                  ),
                ),
              ),
              N("Lophotrochozoa", 564, STR21,
                N("Annelida", 520, APPROX + " (TimeTree 5 gives 631, older than STR21 Lophotrochozoa 564; left as is)"),
                N("Mollusca", 545, APPROX + " (Polyplacophora split; must sit above Conchifera)",
                  N("Conchifera", 534, STR21 + " (Lottia vs Octopus = conchiferan crown)",
                    N("Bivalvia", 485, LI25 + " crown Bivalvia ~485",
                      N("Pteriomorphia", 446, LI25 + " Pectinida vs other pteriomorphians 446 (410-474)",
                        N("Ostreida + Arcida + Mytilida", 421, LI25 + " Ostreida vs Mytilida 421 (384-458)"),
                      ),
                      N("Heterodonta", 470, LI25 + " deep heterodont nodes 467-525",
                        N("Imparidentia", 400, APPROX + " (between Euheterodonta 467 and the 362 node)",
                          N("Core Imparidentia", 362, LI25 + " (Myida+Venerida) vs (Galeommatida+Adapedonta+Cardiida) 362 (310-414)",
                            N("Myida + Venerida", 301, LI25 + " 301 (249-358)"),
                            N("Adapedonta + Cardiida", 300, LI25 + " ~300 (250-348)"),
                          ),
                        ),
                      ),
                    ),
                    N("Gastropoda", 532, ZHANG22 + " Patellogastropoda split 532 (505-548); topology after Uribe et al. 2022 Syst Biol, Cunha & Giribet 2019 differ at the root",
                      N("Orthogastropoda", 493, ZHANG22 + " Vetigastropoda vs Caenogastropoda+relatives 493 (460-521)",
                        N("Vetigastropoda", 370, TANNER17 + " Fig. S4 95% CI 311-432, midpoint"),
                        N("Apogastropoda", 394, TANNER17 + " Fig. S4 95% CI 351-437, midpoint (Caenogastropoda vs Heterobranchia)",
                          N("Caenogastropoda", 260, TANNER17 + " Fig. S4 95% CI 140-310; set at 260 to sit above the TimeTree Neogastropoda crown of 239",
                            N("Neogastropoda", 239, TT5 + " 239; my prior guess 150"),
                          ),
                          N("Heterobranchia", 300, APPROX,
                            N("Stylommatophora", 150, APPROX),
                          ),
                        ),
                      ),
                    ),
                    N("Coleoidea", 289, TANNER17 + " crown Coleoidea 289",
                      N("Octobrachia", 239, TANNER17 + " crown Octobrachia 239 (vampire squid vs octopods)",
                        N("Incirrata", 98, TANNER17 + " crown Incirrata 98"),
                      ),
                      N("Decabrachia", 173, TANNER17 + " crown Decabrachia 173",
                        N("Myopsida", 100, TANNER17 + " Myopsida 100"),
                        N("Oegopsida", 104, TANNER17 + " Oegopsida 104"),
                      ),
                    ),
                  ),
                ),
              ),
            ),
            N("Deuterostomes", 599, STR21,
              N("Echinodermata", 500, APPROX,
                N("Echinozoa", 450, APPROX,
                  N("Echinoidea", 113, TT5 + " 113; my prior guess 250"),
                  N("Holothuroidea", 250, APPROX),
                ),
              ),
              N("Chordates", 560, STR21,
                N("Olfactores", 545, APPROX,
                  N("Tunicata", 300, APPROX),
                  N("Vertebrates", 535, APPROX + " (cyclostome/gnathostome split)",
                    N("Cyclostomata", 480, APPROX),
                    N("Jawed vertebrates", 458, IRI17,
                      S(OPEN + "sharks_vertlife.nwk", "Stein et al. 2018 Nat Ecol Evol 2:288, VertLife shark tree subset (Chond_10Cal), tree 1 of 100", {"Raja binoculata": "Beringraja binoculata", "Himantura gerrardi": "Maculabatis gerrardi"}),
                      N("Bony vertebrates", 449, IRI17,
                        S(OPEN + "actinopt_12k_treePL_tre", "Rabosky et al. 2018 Nature 559:392, Fish Tree of Life actinopt_12k_treePL", RAB18_SYN),
                        N("Lobe-finned fishes + tetrapods", 412, IRI17,
                          T("Protopterus annectens"),
                          N("Tetrapods", 350, IRI17 + " (early Carboniferous; mean approx.)",
                            S(OPEN + "amphibians_vertlife.nwk", "Jetz & Pyron 2018 Nat Ecol Evol 2:850, VertLife amphibian tree subset, tree 1 of 100", {}),
                            N("Amniotes", 325, STR21,
                              S(OPEN + "mamphy_mcc.nwk", "Upham et al. 2019 PLoS Biol 17:e3000494, MamPhy completed 5,911sp NDexp MCC", UPH19_SYN),
                              N("Sauropsids", 280, APPROX + " (lepidosaur/archosaur split)",
                                S(OPEN + "squamates_vertlife.nwk", "Tonini et al. 2016 Biol Conserv 204:23, VertLife squamate tree subset, tree 1 of 100", {}),
                                N("Archosaurs + turtles", 260, APPROX,
                                  N("Testudines", 200, APPROX),
                                  N("Archosaurs", 250, APPROX + " (crocodilians vs birds)",
                                    N("Crocodylia", 90, APPROX),
                                    S(OPEN + "birds_jetz_tree1.nwk", "Jetz et al. 2012 Nature 491:444, birdtree.org Ericson Stage 2 subset, tree 1 of 100", JETZ12_SYN),
                                  ),
                                ),
                              ),
                            ),
                          ),
                        ),
                      ),
                    ),
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    ),
  ),
  N("Diaphoretickes + Discoba", 2114, STR21,
    N("Discoba", 1674, STR21, T("Euglena gracilis")),
    N("Diaphoretickes", 2028, STR21,
      N("SAR", 1741, STR21,
        N("Stramenopiles", 1044, STR21,
          N("Phaeophyceae", 371, CHOI24 + " crown Phaeophyceae 371 (275-474); origin vs Schizocladia 449",
            N("Ishigeales + SSD + BACR", 308, CHOI24 + " 308",
              N("SSD + BACR", 224, CHOI24 + " 224 (177-275)",
                N("BACR", 167, CHOI24 + " brown algal crown radiation 167 (130-206)",
                  N("BACR II-V", 142, CHOI24 + " 142",
                    N("Fucales", 66, CHOI24 + " crown Fucales 66"),
                    N("BACR III-V", 132, CHOI24 + " 132",
                      N("Ectocarpales + Laminariales", 103, CHOI24 + " 103",
                        N("Ectocarpales", 54, CHOI24 + " crown Ectocarpales 54"),
                        N("Laminariales", 83, CHOI24 + " crown Laminariales 83"),
                      ),
                    ),
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
      N("Archaeplastida", 1925, STR21,
        N("Rhodophyta", 1614, STR21,
          N("Bangiophyceae + Florideophyceae", 1415, STR21,
            N("Bangiales", 100, APPROX),
            N("Florideophyceae", 943, YANG16 + " crown (Hildenbrandiophycidae split)",
              N("Nemaliophycidae + higher florideophytes", 661, YANG16 + " Nemaliophycidae split 661",
                N("Nemaliophycidae", 450, APPROX),
                N("Ahnfeltiophycidae + Rhodymeniophycidae", 508, YANG16,
                  N("Rhodymeniophycidae", 450, APPROX,
                    N("Ceramiales", 335, YANG16),
                    N("Gigartinales + Gracilariales + Halymeniales", 400, APPROX,
                      N("Gigartinales", 250, APPROX),
                    ),
                  ),
                ),
              ),
            ),
          ),
        ),
        N("Viridiplantae", 1112, STR21,
          N("Chlorophyta", 972, STR21,
            N("Core Chlorophyta (UTC)", 850, APPROX + " REVIEW (raised to 850 to sit above TimeTree Trebouxiophyceae 827): Strassert node 206 (Coccomyxa vs Volvox) gives 583, but Del Cortona et al. 2020 PNAS and Hou et al. 2022 Nat Commun place the origin of green seaweeds in the Tonian-Cryogenian (>720); topology follows them (Bryopsidales sister to Chlorophyceae, Ulvophyceae s.s. separate)",
              N("Ulvophyceae s.s.", 700, APPROX + " (Tonian-Cryogenian origin per Del Cortona 2020 / Hou 2022)",
                N("Ulvales", 609, TT5 + " Ulva vs Monostroma 609; consistent with Del Cortona 2020 / Hou 2022"),
              ),
              N("Bryopsidales + Chlorophyceae", 750, APPROX + " (topology per Del Cortona 2020)",
                N("Bryopsidales", 400, APPROX),
                N("Chlorophyceae", 400, APPROX),
              ),
              N("Trebouxiophyceae", 827, TT5 + " Chlorella vs Prasiola 827"),
            ),
          ),
          N("Streptophyta", 790, STR21,
            N("Land plants", 534, STR21,
              N("Euphyllophytes", 480, STR21 + " (474; raised to 480 to sit above FTOL's fern crown of 475)",
                S(OPEN + "ftol_dated.nwk", "Nitta et al. 2022 Front Plant Sci, FTOL ML dated tree (ftolr)", {}, groups=["Ferns"]),
                S(OPEN + "v0.1/ALLMB.tre", "Smith & Brown 2018 Am J Bot 105:302, ALLMB (seed plants, Magallon backbone)", SB18_SYN),
              ),
            ),
          ),
        ),
      ),
    ),
  ),
)
