"""Placeholder food tree of life, built from approximate node ages (Ma).

Deep nodes follow published ranges loosely (Parfrey et al. 2011, Strassert et
al. 2021, TimeTree medians as remembered); shallow nodes are educated guesses.
Replace wholesale with a TimeTree-derived Newick + CSV when available.
"""
import json, csv, sys

def N(name, age, *children):
    return {"name": name, "age": float(age), "children": list(children)}

def T(id, common, species, lineage, clade, aliases=""):
    return {"id": id, "common": common, "species": species, "lineage": lineage,
            "clade": clade, "aliases": aliases, "age": 0.0}

A, F, P, G, R, B = "animal", "fungus", "plant", "green", "red", "brown"

tree = N("Eukaryotes (Amorphea / Diaphoretickes)", 1800,
  N("Opisthokonta", 1100,
    N("Fungi", 800,
      T("rhizopus", "tempeh mold", "Rhizopus oligosporus", "Mucoromycota", F, "tempeh"),
      N("Dikarya", 600,
        N("Ascomycota", 500,
          T("yeast", "baker's / brewer's yeast", "Saccharomyces cerevisiae", "Saccharomycetes", F, "yeast;bread;beer;wine;sourdough;leavened"),
          N("Pezizomycotina", 400,
            N("Pezizales", 250,
              N("Tuber", 30,
                T("black-truffle", "black truffle", "Tuber melanosporum", "Pezizales", F, "truffle"),
                T("white-truffle", "white truffle", "Tuber magnatum", "Pezizales", F, "")),
              T("morel", "morel", "Morchella esculenta", "Pezizales", F, "morels")),
            N("Leotiomyceta", 300,
              N("Eurotiales", 100,
                T("koji", "koji mold", "Aspergillus oryzae", "Eurotiales", F, "koji;miso;soy sauce;sake;mirin"),
                N("Penicillium", 20,
                  T("penicillium-roqueforti", "blue cheese mold", "Penicillium roqueforti", "Eurotiales", F, "blue cheese;roquefort;gorgonzola;stilton"),
                  T("penicillium-camemberti", "camembert mold", "Penicillium camemberti", "Eurotiales", F, "brie;camembert"))),
              T("quorn", "mycoprotein", "Fusarium venenatum", "Hypocreales", F, "quorn")))),
        N("Basidiomycota", 550,
          T("huitlacoche", "huitlacoche", "Ustilago maydis", "Ustilaginales", F, "corn smut"),
          N("Agaricomycotina", 450,
            T("snow-fungus", "snow fungus", "Tremella fuciformis", "Tremellales", F, "white fungus"),
            N("Agaricomycetes", 300,
              T("chanterelle", "chanterelle", "Cantharellus cibarius", "Cantharellales", F, ""),
              N("", 280,
                T("wood-ear", "wood ear", "Auricularia auricula-judae", "Auriculariales", F, "black fungus;cloud ear"),
                N("", 260,
                  T("lions-mane", "lion's mane", "Hericium erinaceus", "Russulales", F, ""),
                  N("", 240,
                    T("maitake", "maitake", "Grifola frondosa", "Polyporales", F, "hen of the woods"),
                    N("Agaricomycetidae", 200,
                      T("porcini", "porcini", "Boletus edulis", "Boletales", F, "cep;penny bun"),
                      N("Agaricales", 120,
                        T("button-mushroom", "button / cremini / portobello", "Agaricus bisporus", "Agaricales", F, "mushroom;mushrooms;cremini;portobello;portabella;champignon"),
                        N("", 110,
                          T("oyster-mushroom", "oyster mushroom", "Pleurotus ostreatus", "Agaricales", F, "king oyster"),
                          N("", 90,
                            T("enoki", "enoki", "Flammulina velutipes", "Agaricales", F, "enokitake"),
                            T("shiitake", "shiitake", "Lentinula edodes", "Agaricales", F, ""))))))))))))),
    N("Metazoa", 700,
      T("jellyfish", "edible jellyfish", "Rhopilema esculentum", "Cnidaria", A, ""),
      N("Bilateria", 600,
        N("Deuterostomia", 580,
          N("Echinodermata", 450,
            T("sea-urchin", "sea urchin (uni)", "Mesocentrotus / Strongylocentrotus spp.", "Echinoidea", A, "uni"),
            T("sea-cucumber", "sea cucumber", "Apostichopus japonicus", "Holothuroidea", A, "")),
          N("Chordata", 520,
            T("sea-pineapple", "sea pineapple (tunicate)", "Halocynthia roretzi", "Tunicata", A, "sea squirt;meongge"),
            N("Vertebrata", 500,
              T("lamprey", "lamprey", "Petromyzon marinus", "Petromyzontiformes", A, ""),
              N("Gnathostomata", 460,
                N("Chondrichthyes", 300,
                  T("dogfish", "dogfish / shark", "Squalus acanthias", "Squaliformes", A, "shark;rock salmon"),
                  T("skate", "skate", "Leucoraja / Raja spp.", "Rajiformes", A, "ray")),
                N("Osteichthyes", 430,
                  N("Actinopterygii", 350,
                    T("sturgeon", "sturgeon (caviar)", "Acipenser spp.", "Acipenseriformes", A, "caviar"),
                    N("Teleostei", 300,
                      T("eel", "eel", "Anguilla spp.", "Anguilliformes", A, "unagi;anago"),
                      N("", 260,
                        N("Otocephala", 230,
                          N("Clupeiformes", 60,
                            T("anchovy", "anchovy", "Engraulis spp.", "Clupeiformes", A, "anchovies;fish sauce;nam pla;boquerones"),
                            N("", 30,
                              T("herring", "herring", "Clupea harengus", "Clupeiformes", A, ""),
                              T("sardine", "sardine", "Sardina pilchardus", "Clupeiformes", A, "sardines;pilchard"))),
                          N("Otophysi", 180,
                            T("carp", "carp", "Cyprinus carpio", "Cypriniformes", A, ""),
                            T("catfish", "catfish", "Ictalurus punctatus", "Siluriformes", A, ""))),
                        N("Euteleostei", 230,
                          N("Salmonidae", 20,
                            T("atlantic-salmon", "Atlantic salmon", "Salmo salar", "Salmonidae", A, "salmon;lox;gravlax;smoked salmon"),
                            N("Oncorhynchus", 8,
                              T("rainbow-trout", "rainbow trout", "Oncorhynchus mykiss", "Salmonidae", A, "trout;steelhead"),
                              T("sockeye", "Pacific salmon", "Oncorhynchus nerka", "Salmonidae", A, "sockeye;coho;king salmon;chinook"))),
                          N("Neoteleostei", 150,
                            N("Gadidae", 15,
                              T("haddock", "haddock", "Melanogrammus aeglefinus", "Gadiformes", A, ""),
                              N("", 10,
                                T("cod", "cod", "Gadus morhua", "Gadiformes", A, "bacalao;salt cod"),
                                T("pollock", "pollock", "Gadus chalcogrammus", "Gadiformes", A, "surimi;fish sticks"))),
                            N("Percomorpha", 120,
                              T("tilapia", "tilapia", "Oreochromis niloticus", "Cichlidae", A, ""),
                              N("", 100,
                                N("Carangaria", 80,
                                  N("Pleuronectiformes", 40,
                                    T("halibut", "halibut", "Hippoglossus hippoglossus", "Pleuronectiformes", A, "flounder"),
                                    T("sole", "sole", "Solea solea", "Pleuronectiformes", A, "")),
                                  N("", 60,
                                    T("mahi-mahi", "mahi-mahi", "Coryphaena hippurus", "Coryphaenidae", A, "dorado;dolphinfish"),
                                    T("swordfish", "swordfish", "Xiphias gladius", "Xiphiidae", A, ""))),
                                N("", 95,
                                  N("Scombridae", 45,
                                    T("tuna", "tuna", "Thunnus spp.", "Scombridae", A, "bluefin;yellowfin;albacore;ahi"),
                                    T("mackerel", "mackerel", "Scomber scombrus", "Scombridae", A, "saba")),
                                  N("Eupercaria", 90,
                                    T("sea-bass", "sea bass", "Dicentrarchus labrax", "Moronidae", A, "branzino;striped bass"),
                                    N("", 80,
                                      T("snapper", "snapper", "Lutjanus spp.", "Lutjanidae", A, ""),
                                      T("grouper", "grouper", "Epinephelus spp.", "Serranidae", A, ""))))))))))),
                  N("Tetrapoda", 350,
                    T("frog", "frog legs", "Pelophylax spp.", "Anura", A, ""),
                    N("Amniota", 320,
                      N("Sauropsida", 260,
                        T("snapping-turtle", "snapping turtle", "Chelydra serpentina", "Testudines", A, "turtle"),
                        N("Archosauria", 250,
                          T("alligator", "alligator", "Alligator mississippiensis", "Crocodilia", A, "crocodile"),
                          N("Aves", 100,
                            T("ostrich", "ostrich", "Struthio camelus", "Struthioniformes", A, "emu"),
                            N("Neognathae", 90,
                              T("pigeon", "pigeon / squab", "Columba livia", "Columbiformes", A, "squab"),
                              N("Galloanserae", 80,
                                N("Anseriformes", 20,
                                  T("duck", "duck", "Anas platyrhynchos", "Anseriformes", A, "duck egg;foie gras"),
                                  T("goose", "goose", "Anser anser", "Anseriformes", A, "")),
                                N("Galliformes", 45,
                                  T("guinea-fowl", "guinea fowl", "Numida meleagris", "Galliformes", A, ""),
                                  N("", 40,
                                    T("quail", "quail", "Coturnix coturnix", "Galliformes", A, "quail egg"),
                                    N("Phasianidae", 30,
                                      T("turkey", "turkey", "Meleagris gallopavo", "Galliformes", A, ""),
                                      N("", 20,
                                        T("pheasant", "pheasant", "Phasianus colchicus", "Galliformes", A, ""),
                                        T("chicken", "chicken", "Gallus gallus", "Galliformes", A, "egg;eggs;hen;poultry")))))))))),
                      N("Mammalia", 160,
                        T("kangaroo", "kangaroo", "Macropus spp.", "Diprotodontia", A, ""),
                        N("Boreoeutheria", 95,
                          N("Euarchontoglires", 80,
                            T("guinea-pig", "guinea pig (cuy)", "Cavia porcellus", "Rodentia", A, "cuy"),
                            N("Leporidae", 12,
                              T("rabbit", "rabbit", "Oryctolagus cuniculus", "Lagomorpha", A, ""),
                              T("hare", "hare", "Lepus europaeus", "Lagomorpha", A, ""))),
                          N("Laurasiatheria", 78,
                            T("horse", "horse", "Equus caballus", "Perissodactyla", A, ""),
                            N("Artiodactyla", 65,
                              T("camel", "camel", "Camelus dromedarius", "Tylopoda", A, ""),
                              N("", 62,
                                T("pig", "pig", "Sus scrofa", "Suina", A, "pork;bacon;ham;lard;prosciutto;sausage;pancetta;gelatin"),
                                N("Ruminantia", 28,
                                  N("Cervidae", 8,
                                    T("venison", "deer (venison)", "Odocoileus virginianus", "Cervidae", A, "deer"),
                                    T("red-deer", "red deer / elk", "Cervus elaphus", "Cervidae", A, "elk")),
                                  N("Bovidae", 20,
                                    N("Caprinae", 7,
                                      T("sheep", "sheep", "Ovis aries", "Bovidae", A, "lamb;mutton;feta;pecorino;sheep milk"),
                                      T("goat", "goat", "Capra hircus", "Bovidae", A, "chevre;goat cheese;goat milk")),
                                    N("Bovinae", 12,
                                      T("water-buffalo", "water buffalo", "Bubalus bubalis", "Bovidae", A, "buffalo mozzarella"),
                                      N("Bos / Bison", 3,
                                        T("cattle", "cattle", "Bos taurus", "Bovidae", A, "beef;milk;cheese;butter;cream;yogurt;ghee;steak;veal;whey;parmesan;cheddar;mozzarella;burger;hamburger;cheeseburger;ground beef"),
                                        T("bison", "bison", "Bison bison", "Bovidae", A, "buffalo"))))))))))))))))),
        N("Protostomia", 580,
          N("Mollusca", 530,
            N("Bivalvia", 480,
              N("Pteriomorphia", 440,
                T("oyster", "oyster", "Crassostrea / Magallana spp.", "Ostreida", A, "oysters"),
                N("", 420,
                  T("mussel", "mussel", "Mytilus edulis", "Mytilida", A, "mussels"),
                  T("scallop", "scallop", "Placopecten / Pecten spp.", "Pectinida", A, "scallops"))),
              N("Heterodonta", 300,
                T("cockle", "cockle", "Cerastoderma edule", "Cardiida", A, ""),
                N("", 250,
                  T("razor-clam", "razor clam", "Ensis spp.", "Adapedonta", A, ""),
                  N("", 220,
                    T("hard-clam", "hard clam (quahog)", "Mercenaria mercenaria", "Venerida", A, "clam;clams;quahog;littleneck;cherrystone;manila clam"),
                    N("", 200,
                      T("soft-shell-clam", "soft-shell clam (steamer)", "Mya arenaria", "Myida", A, "steamers"),
                      T("geoduck", "geoduck", "Panopea generosa", "Adapedonta", A, "")))))),
            N("", 500,
              N("Gastropoda", 450,
                T("abalone", "abalone", "Haliotis spp.", "Vetigastropoda", A, ""),
                N("", 400,
                  T("escargot", "land snail (escargot)", "Helix pomatia", "Stylommatophora", A, "snail;snails"),
                  N("Caenogastropoda", 200,
                    T("periwinkle", "periwinkle", "Littorina littorea", "Littorinimorpha", A, "winkle;winkles"),
                    N("", 180,
                      T("whelk", "whelk", "Buccinum undatum", "Neogastropoda", A, ""),
                      T("conch", "queen conch", "Aliger gigas", "Littorinimorpha", A, ""))))),
              N("Coleoidea", 260,
                T("octopus", "octopus", "Octopus vulgaris", "Octopoda", A, "pulpo;tako"),
                N("Decapodiformes", 150,
                  T("squid", "squid", "Doryteuthis / Loligo spp.", "Myopsida", A, "calamari;ika"),
                  T("cuttlefish", "cuttlefish", "Sepia officinalis", "Sepiida", A, ""))))),
          N("Pancrustacea", 500,
            N("Malacostraca", 420,
              T("krill", "krill", "Euphausia superba", "Euphausiacea", A, ""),
              N("Decapoda", 380,
                T("shrimp", "shrimp", "Penaeus / Litopenaeus spp.", "Dendrobranchiata", A, "prawns;prawn;ebi"),
                N("Pleocyemata", 350,
                  T("freshwater-prawn", "freshwater prawn", "Macrobrachium rosenbergii", "Caridea", A, ""),
                  N("Reptantia", 300,
                    N("Astacidea", 250,
                      T("lobster", "lobster", "Homarus americanus", "Astacidea", A, ""),
                      T("crayfish", "crayfish", "Procambarus clarkii", "Astacidea", A, "crawfish;crawdad")),
                    N("", 260,
                      T("king-crab", "king crab", "Paralithodes camtschaticus", "Anomura", A, ""),
                      N("Brachyura", 120,
                        T("blue-crab", "blue crab", "Callinectes sapidus", "Brachyura", A, "crab;crabs;crab meat"),
                        T("dungeness-crab", "Dungeness crab", "Metacarcinus magister", "Brachyura", A, ""))))))),
            N("Hexapoda", 400,
              N("Orthoptera", 200,
                T("cricket", "cricket", "Acheta domesticus", "Orthoptera", A, "crickets;cricket flour"),
                T("grasshopper", "grasshopper", "Sphenarium / Locusta spp.", "Orthoptera", A, "chapulines;locust")),
              N("Holometabola", 330,
                T("honeybee", "honey bee (honey)", "Apis mellifera", "Hymenoptera", A, "honey;royal jelly;bee pollen"),
                N("", 300,
                  T("mealworm", "mealworm", "Tenebrio molitor", "Coleoptera", A, ""),
                  T("silkworm", "silkworm pupa", "Bombyx mori", "Lepidoptera", A, "beondegi"))))))))),
  N("Diaphoretickes", 1700,
    N("Phaeophyceae (brown algae)", 100,
      N("Laminariales", 30,
        T("kombu", "kombu (kelp)", "Saccharina japonica", "Laminariales", B, "kelp;dashi;kelp noodles;laminaria"),
        N("Alariaceae", 15,
          T("wakame", "wakame", "Undaria pinnatifida", "Laminariales", B, ""),
          T("alaria", "winged kelp", "Alaria esculenta", "Laminariales", B, ""))),
      N("Fucales", 60,
        T("hijiki", "hijiki", "Sargassum fusiforme", "Fucales", B, ""),
        N("Fucaceae", 30,
          T("rockweed", "rockweed", "Ascophyllum nodosum", "Fucales", B, "knotted wrack"),
          T("bladderwrack", "bladderwrack", "Fucus vesiculosus", "Fucales", B, "")))),
    N("Archaeplastida", 1500,
      N("Rhodophyta (red algae)", 1000,
        N("Bangiales", 60,
          T("nori", "nori", "Pyropia yezoensis", "Bangiales", R, "seaweed;sushi seaweed;gim;kim"),
          T("laver", "laver", "Porphyra umbilicalis", "Bangiales", R, "laverbread")),
        N("Florideophyceae", 600,
          T("dulse", "dulse", "Palmaria palmata", "Palmariales", R, ""),
          N("", 400,
            T("agar", "agar (Gelidium)", "Gelidium spp.", "Gelidiales", R, "agar-agar;kanten"),
            N("", 300,
              T("irish-moss", "Irish moss (carrageenan)", "Chondrus crispus", "Gigartinales", R, "carrageenan"),
              T("ogo", "ogo (Gracilaria)", "Gracilaria spp.", "Gracilariales", R, "gracilaria"))))),
      N("Viridiplantae", 1000,
        N("Chlorophyta (green algae)", 600,
          T("chlorella", "chlorella", "Chlorella vulgaris", "Chlorellales", G, ""),
          N("Ulvophyceae", 400,
            T("sea-lettuce", "sea lettuce", "Ulva lactuca", "Ulvales", G, "aonori;aosa;ulva;ao-nori"),
            T("sea-grapes", "sea grapes", "Caulerpa lentillifera", "Bryopsidales", G, "umibudo"))),
        N("Euphyllophyta", 400,
          T("fiddlehead", "fiddlehead fern", "Matteuccia struthiopteris", "Polypodiales", P, "ostrich fern"),
          N("Spermatophyta", 320,
            N("Gymnosperms", 300,
              T("ginkgo", "ginkgo nut", "Ginkgo biloba", "Ginkgoales", P, ""),
              N("Conifers", 250,
                T("juniper", "juniper berry", "Juniperus communis", "Cupressaceae", P, "gin"),
                N("Pinus", 40,
                  T("pine-nut", "pine nut (stone pine)", "Pinus pinea", "Pinaceae", P, "pignoli;pinoli"),
                  T("korean-pine-nut", "Korean pine nut", "Pinus koraiensis", "Pinaceae", P, "")))),
            N("Angiosperms", 150,
              N("Magnoliids", 130,
                T("black-pepper", "black pepper", "Piper nigrum", "Piperales", P, "pepper;peppercorn;white pepper"),
                N("", 120,
                  T("nutmeg", "nutmeg / mace", "Myristica fragrans", "Magnoliales", P, "mace"),
                  N("Lauraceae", 60,
                    T("avocado", "avocado", "Persea americana", "Laurales", P, "guacamole"),
                    N("", 40,
                      T("cinnamon", "cinnamon", "Cinnamomum verum", "Laurales", P, "cassia"),
                      T("bay-leaf", "bay leaf", "Laurus nobilis", "Laurales", P, "bay"))))),
              N("", 145,
                N("Monocots", 135,
                  T("taro", "taro", "Colocasia esculenta", "Alismatales", P, "poi;dasheen"),
                  N("", 125,
                    T("yam", "yam", "Dioscorea spp.", "Dioscoreales", P, "ube;nagaimo"),
                    N("", 120,
                      N("Asparagales", 100,
                        T("vanilla", "vanilla", "Vanilla planifolia", "Orchidaceae", P, ""),
                        N("", 80,
                          T("asparagus", "asparagus", "Asparagus officinalis", "Asparagaceae", P, ""),
                          N("Allium", 15,
                            T("chive", "chive", "Allium schoenoprasum", "Amaryllidaceae", P, "chives"),
                            N("", 12,
                              T("leek", "leek", "Allium ampeloprasum", "Amaryllidaceae", P, "leeks;elephant garlic"),
                              N("", 10,
                                T("onion", "onion", "Allium cepa", "Amaryllidaceae", P, "onions;shallot;shallots;scallion;scallions;green onion;spring onion"),
                                T("garlic", "garlic", "Allium sativum", "Amaryllidaceae", P, "")))))),
                      N("Commelinids", 115,
                        N("Arecaceae", 60,
                          T("date", "date palm", "Phoenix dactylifera", "Arecaceae", P, "dates"),
                          N("", 50,
                            T("coconut", "coconut", "Cocos nucifera", "Arecaceae", P, "coconut milk;coconut oil;coconut cream"),
                            T("oil-palm", "oil palm", "Elaeis guineensis", "Arecaceae", P, "palm oil;palm sugar"))),
                        N("", 110,
                          N("Zingiberales", 80,
                            T("banana", "banana / plantain", "Musa spp.", "Musaceae", P, "plantain;plantains"),
                            N("Zingiberaceae", 40,
                              T("cardamom", "cardamom", "Elettaria cardamomum", "Zingiberaceae", P, ""),
                              N("", 30,
                                T("ginger", "ginger", "Zingiber officinale", "Zingiberaceae", P, ""),
                                T("turmeric", "turmeric", "Curcuma longa", "Zingiberaceae", P, "")))),
                          N("Poales", 100,
                            T("pineapple", "pineapple", "Ananas comosus", "Bromeliaceae", P, ""),
                            N("Poaceae", 75,
                              N("BEP clade", 50,
                                T("rice", "rice", "Oryza sativa", "Poaceae", P, "sushi rice;rice vinegar;rice noodles;rice flour;mochi;sake"),
                                N("Pooideae", 30,
                                  T("oat", "oat", "Avena sativa", "Poaceae", P, "oats;oatmeal;rolled oats"),
                                  N("Triticeae", 12,
                                    T("barley", "barley", "Hordeum vulgare", "Poaceae", P, "malt;beer;pearl barley"),
                                    N("", 5,
                                      T("wheat", "wheat", "Triticum aestivum", "Poaceae", P, "flour;bread;pasta;noodles;bun;couscous;bulgur;semolina;durum;seitan;soy sauce;tortilla;crackers;breadcrumbs;panko;pastry"),
                                      T("rye", "rye", "Secale cereale", "Poaceae", P, ""))))),
                              N("PACMAD clade", 30,
                                T("millet", "millet", "Pennisetum / Panicum spp.", "Poaceae", P, "pearl millet;proso"),
                                N("", 12,
                                  T("maize", "maize (corn)", "Zea mays", "Poaceae", P, "corn;cornmeal;polenta;masa;corn syrup;cornstarch;popcorn;grits;tortilla"),
                                  N("", 8,
                                    T("sorghum", "sorghum", "Sorghum bicolor", "Poaceae", P, ""),
                                    T("sugarcane", "sugarcane", "Saccharum officinarum", "Poaceae", P, "sugar;cane sugar;molasses;rum;brown sugar"))))))))))),
                N("Eudicots", 130,
                  T("poppy-seed", "poppy seed", "Papaver somniferum", "Ranunculales", P, ""),
                  N("", 125,
                    N("Proteales", 110,
                      T("lotus", "lotus root", "Nelumbo nucifera", "Nelumbonaceae", P, ""),
                      T("macadamia", "macadamia", "Macadamia integrifolia", "Proteaceae", P, "")),
                    N("Pentapetalae", 115,
                      T("currant", "currant / gooseberry", "Ribes spp.", "Saxifragales", P, "blackcurrant;gooseberry;cassis"),
                      N("", 112,
                        N("Caryophyllales", 90,
                          N("Polygonaceae", 50,
                            T("buckwheat", "buckwheat", "Fagopyrum esculentum", "Polygonaceae", P, "soba;kasha"),
                            T("rhubarb", "rhubarb", "Rheum rhabarbarum", "Polygonaceae", P, "")),
                          N("", 75,
                            T("prickly-pear", "prickly pear (nopal)", "Opuntia ficus-indica", "Cactaceae", P, "nopales;cactus"),
                            N("Amaranthaceae", 60,
                              T("amaranth", "amaranth", "Amaranthus spp.", "Amaranthaceae", P, ""),
                              N("", 55,
                                T("beet", "beet / chard / sugar beet", "Beta vulgaris", "Amaranthaceae", P, "beetroot;chard;swiss chard;beet sugar"),
                                N("", 40,
                                  T("spinach", "spinach", "Spinacia oleracea", "Amaranthaceae", P, ""),
                                  T("quinoa", "quinoa", "Chenopodium quinoa", "Amaranthaceae", P, "")))))),
                        N("", 110,
                          N("Rosids", 108,
                            T("grape", "grape", "Vitis vinifera", "Vitales", P, "wine;raisin;raisins;grapes;wine vinegar;balsamic"),
                            N("", 105,
                              N("Fabids", 100,
                                N("Malpighiales", 80,
                                  T("cassava", "cassava", "Manihot esculenta", "Euphorbiaceae", P, "tapioca;yuca;manioc"),
                                  T("passionfruit", "passion fruit", "Passiflora edulis", "Passifloraceae", P, "")),
                                N("Nitrogen-fixing clade", 95,
                                  N("Fabaceae", 65,
                                    T("tamarind", "tamarind", "Tamarindus indica", "Fabaceae", P, ""),
                                    N("", 60,
                                      T("carob", "carob", "Ceratonia siliqua", "Fabaceae", P, ""),
                                      N("Papilionoideae", 58,
                                        T("peanut", "peanut", "Arachis hypogaea", "Fabaceae", P, "peanuts;peanut butter;groundnut"),
                                        N("", 50,
                                          N("Phaseoloids", 20,
                                            T("soy", "soybean", "Glycine max", "Fabaceae", P, "soy;tofu;soy sauce;miso;edamame;tempeh;soy milk;natto;tamari"),
                                            N("", 8,
                                              T("common-bean", "common bean", "Phaseolus vulgaris", "Fabaceae", P, "black beans;kidney beans;pinto;green beans;navy beans;cannellini"),
                                              N("Vigna", 3,
                                                T("mung-bean", "mung bean", "Vigna radiata", "Fabaceae", P, "bean sprouts"),
                                                T("cowpea", "cowpea / black-eyed pea", "Vigna unguiculata", "Fabaceae", P, "black-eyed peas")))),
                                          N("IRLC", 25,
                                            T("licorice", "licorice", "Glycyrrhiza glabra", "Fabaceae", P, ""),
                                            N("", 22,
                                              T("chickpea", "chickpea", "Cicer arietinum", "Fabaceae", P, "garbanzo;hummus;chana"),
                                              N("", 18,
                                                T("fenugreek", "fenugreek", "Trigonella foenum-graecum", "Fabaceae", P, "methi"),
                                                N("", 15,
                                                  T("fava", "fava bean", "Vicia faba", "Fabaceae", P, "broad bean"),
                                                  N("", 12,
                                                    T("pea", "pea", "Pisum sativum", "Fabaceae", P, "peas;split peas;snap peas"),
                                                    T("lentil", "lentil", "Lens culinaris", "Fabaceae", P, "lentils;dal")))))))))),
                                  N("", 92,
                                    N("Rosales", 90,
                                      N("Rosaceae", 85,
                                        N("Rosoideae", 55,
                                          T("strawberry", "strawberry", "Fragaria x ananassa", "Rosaceae", P, "strawberries"),
                                          N("Rubus", 10,
                                            T("raspberry", "raspberry", "Rubus idaeus", "Rosaceae", P, "raspberries"),
                                            T("blackberry", "blackberry", "Rubus fruticosus agg.", "Rosaceae", P, "blackberries"))),
                                        N("Amygdaloideae", 60,
                                          N("Maleae", 20,
                                            T("apple", "apple", "Malus domestica", "Rosaceae", P, "cider;apples;applesauce"),
                                            N("", 15,
                                              T("pear", "pear", "Pyrus communis", "Rosaceae", P, ""),
                                              T("quince", "quince", "Cydonia oblonga", "Rosaceae", P, ""))),
                                          N("Prunus", 25,
                                            T("cherry", "cherry", "Prunus avium", "Rosaceae", P, "cherries;sour cherry"),
                                            N("", 15,
                                              N("", 5,
                                                T("peach", "peach / nectarine", "Prunus persica", "Rosaceae", P, "nectarine"),
                                                T("almond", "almond", "Prunus dulcis", "Rosaceae", P, "almonds;marzipan;almond milk")),
                                              N("", 8,
                                                T("plum", "plum", "Prunus domestica", "Rosaceae", P, "prune;prunes;umeboshi"),
                                                T("apricot", "apricot", "Prunus armeniaca", "Rosaceae", P, "")))))),
                                      N("", 75,
                                        N("Cannabaceae", 20,
                                          T("hops", "hops", "Humulus lupulus", "Cannabaceae", P, "beer;ipa"),
                                          T("hemp", "hemp seed", "Cannabis sativa", "Cannabaceae", P, "")),
                                        N("Moraceae", 60,
                                          T("fig", "fig", "Ficus carica", "Moraceae", P, "figs"),
                                          N("", 40,
                                            T("mulberry", "mulberry", "Morus spp.", "Moraceae", P, ""),
                                            N("Artocarpus", 15,
                                              T("jackfruit", "jackfruit", "Artocarpus heterophyllus", "Moraceae", P, ""),
                                              T("breadfruit", "breadfruit", "Artocarpus altilis", "Moraceae", P, "")))))),
                                    N("", 85,
                                      N("Cucurbitaceae", 50,
                                        T("bitter-melon", "bitter melon", "Momordica charantia", "Cucurbitaceae", P, "bitter gourd"),
                                        N("", 45,
                                          N("Cucurbita", 5,
                                            T("zucchini", "zucchini / pumpkin (C. pepo)", "Cucurbita pepo", "Cucurbitaceae", P, "summer squash;pumpkin;acorn squash;courgette;pepitas"),
                                            T("butternut", "butternut / kabocha", "Cucurbita moschata / maxima", "Cucurbitaceae", P, "winter squash;kabocha;hubbard")),
                                          N("", 30,
                                            T("watermelon", "watermelon", "Citrullus lanatus", "Cucurbitaceae", P, ""),
                                            N("Cucumis", 10,
                                              T("cucumber", "cucumber", "Cucumis sativus", "Cucurbitaceae", P, "pickle;pickles;gherkin"),
                                              T("melon", "melon (cantaloupe, honeydew)", "Cucumis melo", "Cucurbitaceae", P, "cantaloupe;honeydew"))))),
                                      N("Fagales", 80,
                                        N("Fagaceae", 60,
                                          T("chestnut", "chestnut", "Castanea spp.", "Fagaceae", P, "chestnuts"),
                                          T("acorn", "acorn", "Quercus spp.", "Fagaceae", P, "oak")),
                                        N("", 70,
                                          T("hazelnut", "hazelnut", "Corylus avellana", "Betulaceae", P, "filbert;hazelnuts"),
                                          N("Juglandaceae", 40,
                                            T("walnut", "walnut", "Juglans regia", "Juglandaceae", P, "walnuts"),
                                            T("pecan", "pecan", "Carya illinoinensis", "Juglandaceae", P, "pecans")))))))),
                              N("Malvids", 100,
                                N("Myrtales", 85,
                                  T("pomegranate", "pomegranate", "Punica granatum", "Lythraceae", P, ""),
                                  N("Myrtaceae", 60,
                                    T("guava", "guava", "Psidium guajava", "Myrtaceae", P, ""),
                                    N("", 55,
                                      T("clove", "clove", "Syzygium aromaticum", "Myrtaceae", P, "cloves"),
                                      T("allspice", "allspice", "Pimenta dioica", "Myrtaceae", P, "")))),
                                N("", 95,
                                  N("Sapindales", 80,
                                    N("Citrus", 8,
                                      T("lime", "lime", "Citrus aurantiifolia", "Rutaceae", P, "key lime;makrut"),
                                      N("", 5,
                                        T("lemon", "lemon", "Citrus limon", "Rutaceae", P, "lemons"),
                                        N("", 3,
                                          T("grapefruit", "grapefruit", "Citrus paradisi", "Rutaceae", P, "pomelo"),
                                          N("", 2,
                                            T("orange", "orange", "Citrus sinensis", "Rutaceae", P, "oranges;orange juice"),
                                            T("mandarin", "mandarin", "Citrus reticulata", "Rutaceae", P, "clementine;tangerine;satsuma"))))),
                                    N("", 70,
                                      N("Sapindaceae", 60,
                                        T("maple", "maple (syrup)", "Acer saccharum", "Sapindaceae", P, "maple syrup"),
                                        T("lychee", "lychee", "Litchi chinensis", "Sapindaceae", P, "")),
                                      N("Anacardiaceae", 45,
                                        T("mango", "mango", "Mangifera indica", "Anacardiaceae", P, ""),
                                        N("", 42,
                                          T("sumac", "sumac", "Rhus coriaria", "Anacardiaceae", P, "za'atar"),
                                          N("", 40,
                                            T("cashew", "cashew", "Anacardium occidentale", "Anacardiaceae", P, "cashews"),
                                            T("pistachio", "pistachio", "Pistacia vera", "Anacardiaceae", P, "pistachios")))))),
                                  N("", 90,
                                    N("Brassicales", 75,
                                      T("papaya", "papaya", "Carica papaya", "Caricaceae", P, ""),
                                      N("", 70,
                                        T("caper", "caper", "Capparis spinosa", "Capparaceae", P, "capers"),
                                        N("Brassicaceae", 35,
                                          N("Cardamineae", 20,
                                            T("watercress", "watercress", "Nasturtium officinale", "Brassicaceae", P, ""),
                                            N("", 10,
                                              T("horseradish", "horseradish", "Armoracia rusticana", "Brassicaceae", P, ""),
                                              T("wasabi", "wasabi", "Eutrema japonicum", "Brassicaceae", P, ""))),
                                          N("Brassiceae", 20,
                                            T("arugula", "arugula", "Eruca vesicaria", "Brassicaceae", P, "rocket"),
                                            N("", 15,
                                              T("radish", "radish", "Raphanus sativus", "Brassicaceae", P, "daikon"),
                                              N("", 12,
                                                T("white-mustard", "white mustard / yellow mustard", "Sinapis alba", "Brassicaceae", P, "mustard;yellow mustard;mustard seed"),
                                                N("", 8,
                                                  T("brown-mustard", "brown mustard / mustard greens", "Brassica juncea", "Brassicaceae", P, "dijon;mustard greens;gai choy"),
                                                  N("Brassica", 4,
                                                    T("turnip", "turnip / bok choy / napa", "Brassica rapa", "Brassicaceae", P, "bok choy;napa cabbage;pak choi;turnip greens;mizuna;rapini"),
                                                    N("", 3,
                                                      T("cabbage", "cabbage / kale / broccoli", "Brassica oleracea", "Brassicaceae", P, "kale;broccoli;cauliflower;brussels sprouts;collard;kohlrabi;sauerkraut;kimchi;coleslaw"),
                                                      T("canola", "canola / rutabaga", "Brassica napus", "Brassicaceae", P, "rapeseed;canola oil;rutabaga;swede"))))))))),
                                    N("Malvaceae", 65,
                                      T("durian", "durian", "Durio zibethinus", "Malvaceae", P, ""),
                                      N("", 55,
                                        T("cacao", "cacao", "Theobroma cacao", "Malvaceae", P, "chocolate;cocoa"),
                                        N("", 50,
                                          T("okra", "okra", "Abelmoschus esculentus", "Malvaceae", P, ""),
                                          T("roselle", "roselle (hibiscus)", "Hibiscus sabdariffa", "Malvaceae", P, "hibiscus;jamaica")))))))))),
                          N("Asterids", 108,
                            N("Ericales", 90,
                              T("brazil-nut", "Brazil nut", "Bertholletia excelsa", "Lecythidaceae", P, ""),
                              N("", 85,
                                T("persimmon", "persimmon", "Diospyros kaki", "Ebenaceae", P, ""),
                                N("", 75,
                                  T("tea", "tea", "Camellia sinensis", "Theaceae", P, "green tea;black tea;matcha;oolong"),
                                  N("", 65,
                                    T("kiwi", "kiwi", "Actinidia deliciosa", "Actinidiaceae", P, "kiwifruit"),
                                    N("Vaccinium", 15,
                                      T("blueberry", "blueberry", "Vaccinium corymbosum", "Ericaceae", P, "blueberries"),
                                      N("", 12,
                                        T("cranberry", "cranberry", "Vaccinium macrocarpon", "Ericaceae", P, "cranberries"),
                                        T("lingonberry", "lingonberry", "Vaccinium vitis-idaea", "Ericaceae", P, ""))))))),
                            N("", 100,
                              N("Lamiids", 95,
                                N("Solanales", 60,
                                  T("sweet-potato", "sweet potato", "Ipomoea batatas", "Convolvulaceae", P, "yam (US);camote"),
                                  N("Solanaceae", 20,
                                    T("tomatillo", "tomatillo", "Physalis philadelphica", "Solanaceae", P, "goldenberry"),
                                    N("", 17,
                                      N("Capsicum", 3,
                                        T("chili", "chili / bell pepper", "Capsicum annuum", "Solanaceae", P, "bell pepper;jalapeno;paprika;cayenne;chile;chilli;red pepper flakes"),
                                        T("habanero", "habanero / scotch bonnet", "Capsicum chinense", "Solanaceae", P, "scotch bonnet")),
                                      N("Solanum", 14,
                                        T("eggplant", "eggplant", "Solanum melongena", "Solanaceae", P, "aubergine"),
                                        N("", 8,
                                          T("tomato", "tomato", "Solanum lycopersicum", "Solanaceae", P, "tomatoes;ketchup;catsup;tomato paste;marinara;salsa"),
                                          T("potato", "potato", "Solanum tuberosum", "Solanaceae", P, "potatoes;fries;french fries;chips")))))),
                                N("", 90,
                                  N("Coffea", 5,
                                    T("coffee", "coffee (arabica)", "Coffea arabica", "Rubiaceae", P, "espresso"),
                                    T("robusta", "robusta coffee", "Coffea canephora", "Rubiaceae", P, "")),
                                  N("Lamiales", 75,
                                    T("olive", "olive", "Olea europaea", "Oleaceae", P, "olive oil;olives"),
                                    N("", 65,
                                      T("sesame", "sesame", "Sesamum indicum", "Pedaliaceae", P, "tahini;sesame oil;sesame seeds"),
                                      N("Lamiaceae", 45,
                                        T("shiso", "shiso (perilla)", "Perilla frutescens", "Lamiaceae", P, "perilla"),
                                        N("Nepetoideae", 35,
                                          N("Ocimeae", 20,
                                            T("basil", "basil", "Ocimum basilicum", "Lamiaceae", P, "thai basil;pesto"),
                                            T("lavender", "lavender", "Lavandula angustifolia", "Lamiaceae", P, "")),
                                          N("Mentheae", 30,
                                            N("Salvia", 15,
                                              T("sage", "sage", "Salvia officinalis", "Lamiaceae", P, ""),
                                              T("rosemary", "rosemary", "Salvia rosmarinus", "Lamiaceae", P, "")),
                                            N("", 18,
                                              N("Mentha", 3,
                                                T("spearmint", "mint (spearmint)", "Mentha spicata", "Lamiaceae", P, "mint"),
                                                T("peppermint", "peppermint", "Mentha x piperita", "Lamiaceae", P, "")),
                                              N("", 12,
                                                N("Origanum", 5,
                                                  T("oregano", "oregano", "Origanum vulgare", "Lamiaceae", P, ""),
                                                  T("marjoram", "marjoram", "Origanum majorana", "Lamiaceae", P, "")),
                                                T("thyme", "thyme", "Thymus vulgaris", "Lamiaceae", P, "")))))))))),
                              N("Campanulids", 95,
                                T("elderberry", "elderberry / elderflower", "Sambucus nigra", "Adoxaceae", P, "elderflower"),
                                N("", 90,
                                  N("Apiaceae", 50,
                                    T("cilantro", "cilantro / coriander", "Coriandrum sativum", "Apiaceae", P, "coriander"),
                                    N("", 45,
                                      N("", 25,
                                        T("carrot", "carrot", "Daucus carota", "Apiaceae", P, "carrots"),
                                        T("cumin", "cumin", "Cuminum cyminum", "Apiaceae", P, "")),
                                      N("", 40,
                                        T("parsnip", "parsnip", "Pastinaca sativa", "Apiaceae", P, ""),
                                        N("", 35,
                                          T("caraway", "caraway", "Carum carvi", "Apiaceae", P, ""),
                                          N("", 30,
                                            N("", 15,
                                              T("celery", "celery / celeriac", "Apium graveolens", "Apiaceae", P, "celeriac;celery seed"),
                                              T("parsley", "parsley", "Petroselinum crispum", "Apiaceae", P, "")),
                                            N("", 20,
                                              T("anise", "anise", "Pimpinella anisum", "Apiaceae", P, "aniseed"),
                                              N("", 10,
                                                T("dill", "dill", "Anethum graveolens", "Apiaceae", P, ""),
                                                T("fennel", "fennel", "Foeniculum vulgare", "Apiaceae", P, "fennel seed")))))))),
                                  N("Asteraceae", 50,
                                    T("artichoke", "artichoke / cardoon", "Cynara cardunculus", "Asteraceae", P, "cardoon"),
                                    N("", 40,
                                      N("Cichorieae", 20,
                                        T("dandelion", "dandelion", "Taraxacum officinale", "Asteraceae", P, ""),
                                        N("", 15,
                                          T("lettuce", "lettuce", "Lactuca sativa", "Asteraceae", P, "romaine;iceberg;salad greens;mesclun"),
                                          N("Cichorium", 8,
                                            T("chicory", "chicory / radicchio", "Cichorium intybus", "Asteraceae", P, "radicchio;belgian endive;witloof"),
                                            T("endive", "endive / escarole", "Cichorium endivia", "Asteraceae", P, "escarole;frisee")))),
                                      N("Asteroideae", 30,
                                        N("", 25,
                                          T("sunflower", "sunflower", "Helianthus annuus", "Asteraceae", P, "sunflower oil;sunflower seeds"),
                                          T("stevia", "stevia", "Stevia rebaudiana", "Asteraceae", P, "")),
                                        N("", 28,
                                          T("chamomile", "chamomile", "Matricaria chamomilla", "Asteraceae", P, ""),
                                          T("tarragon", "tarragon", "Artemisia dracunculus", "Asteraceae", P, "wormwood;absinthe"))))))))))))))))))))))

# ---- validate & emit ----
tips, internals = [], []
ids = set()
def walk(node, parent_age):
    if "children" in node:
        assert parent_age is None or node["age"] < parent_age, (node["name"], node["age"], parent_age)
        internals.append(node)
        for c in node["children"]:
            walk(c, node["age"])
    else:
        assert node["id"] not in ids, node["id"]
        ids.add(node["id"]); tips.append(node)
walk(tree, None)

def total_bl(node, parent_age=None):
    s = 0.0 if parent_age is None else parent_age - node["age"]
    for c in node.get("children", []):
        s += total_bl(c, node["age"])
    return s

def newick(node, parent_age=None):
    bl = "" if parent_age is None else f":{parent_age - node['age']:g}"
    if "children" in node:
        inner = ",".join(newick(c, node["age"]) for c in node["children"])
        label = node["name"].replace(" ", "_").replace("(", "").replace(")", "").replace("/", "-").replace(",", "")
        return f"({inner}){label}{bl}"
    return f"{node['id']}{bl}"

print(f"tips: {len(tips)}  internal nodes: {len(internals)}  total branch length: {total_bl(tree):.0f} Myr", file=sys.stderr)

with open("food_tree.newick", "w") as f:
    f.write(newick(tree) + ";\n")
with open("taxa.csv", "w", newline="") as f:
    w = csv.writer(f)
    w.writerow(["id", "common_name", "species", "lineage", "clade", "aliases"])
    for t in tips:
        w.writerow([t["id"], t["common"], t["species"], t["lineage"], t["clade"], t["aliases"]])
with open("food_tree.json", "w") as f:
    json.dump(tree, f, separators=(",", ":"))
